export enum UserActionType {
    REQUEST_USER = 'REQUEST_USER',
    RECEIVE_USER = 'RECEIVE_USER',
    ERROR_USER = 'ERROR_USER',
    REQUEST_RESUME = 'REQUEST_RESUME',
    RECEIVE_RESUME = 'RECEIVE_RESUME',
    ERROR_RESUME = 'ERROR_RESUME'
}
