export enum VacanciesType {
    REQUEST_VACANCIES = 'REQUEST_VACANCIES',
    RECEIVE_VACANCIES = 'RECEIVE_VACANCIES',
    RECEIVE_MORE_VACANCIES = 'RECEIVE_MORE_VACANCIES',
    ERROR_VACANCIES = 'ERROR_VACANCIES'
}
